"""add initial_check

Revision ID: bd88966438e9
Revises: 9d0e7ac8b98a
Create Date: 2025-12-13 01:03:03.061443

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'bd88966438e9'
down_revision: Union[str, Sequence[str], None] = '9d0e7ac8b98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    This revision was generated by mistake and duplicates the base schema
    already created in 9d0e7ac8b98a. Keep it as a no-op so databases can
    advance through the existing revision chain without attempting to
    recreate the same tables.
    """
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
